version: '3'

services:
  # Vue Frontend 추가
  frontend:
    image: sumin22/erppro-frontend:v1.0
    container_name: "frontend"
    ports:
      - "8080:80"  # 프론트엔드 앱을 외부에서 접근할 수 있도록 포트 80에 바인딩
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production  # Vue의 환경 설정, production 모드
      - VUE_APP_KAKAO_API_KEY=${VUE_APP_KAKAO_API_KEY}  # .env에서 환경 변수 가져오기

    networks:
      - app-network

  # Spring Boot WAS1
  was1:
    build: .
    container_name: "was1"
    image: "sumin22/erppro:v1.0"
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    networks:
      - app-network

  # Spring Boot WAS2
  was2:
    build: .
    image: "sumin22/erppro:v1.0"
    container_name: "was2"
    ports:
      - "8082:8081"
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx
    container_name: "webserver"
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - was1
      - was2
    networks:
      - app-network
networks:
  app-network:
    driver: bridge