spring:
  datasource:
    url: jdbc:mysql://hoteldb.cyzrnn6eoqnk.ap-northeast-2.rds.amazonaws.com:3306/hotel?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: test1234
