spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret
server:
  env: blue


---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8081
  serverAddress: localhost

serverName: local_server

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8081
  serverAddress: 3.34.197.241

serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8082
  serverAddress: 3.34.197.241

serverName: green_server


---
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/final_project?characterEncoding=utf8&useUnicode=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
